### ISSUE TITLE
Installation instructions or guidance

### ISSUE THREAD

**Issue by timtyrrell** [zsh-vi-more/vi-motions#3]
My apologies, but can you give me guidance on how to install this plugin? I tried with zcomet: `zcomet load zsh-vi-more/vi-motions` and now get the following in  my prompt:

```
(anon):autoload:6: bad option: -s
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
(anon):autoload:6: bad option: -v
```

Thanks so much for your time, I look forward to using the plugin 🏆

**Comment by xPMo** [comment]
Hi and sorry for the wait! IRL is what it is.

I found the issue in `zcomet` and made a PR there with the fix. I'll close this when it gets merged.

**Comment by agkozak** [comment]
@xPMo I don't see the PR, so I went ahead and merged your patch. Thanks very much -- that was an oversight on my part.

@xPMo @timtyrrell Thank you both for making `zcomet` better.

**Comment by timtyrrell** [comment]
Test and fixed! Thanks to both of you ❤️
